proyecto_lo_de_lali/apps/cuentas/urls.py
from django.urls import path
from .views import Cuentas, index

urlpatterns = [
    path('home/', index, name='inicio'),
    path('cargar_cuentas/', Cuentas.cargar_cuentas, name='cargar_cuentas' ),
    path('lista_clientes/', Cuentas.listar, name='lista_clientes'),
    path('resumen_cliente/<int:id_cliente>', Cuentas.cargar_resumen, name="cargar_resumen"),
    path('ver_resumen/<int:id_cliente>', Cuentas.ver_resumen, name="ver_resumen"),
    path('eliminar_cuenta/<int:id_cliente>', Cuentas.eliminar_cuenta, name="eliminar_cuenta"),
]

proyecto_lo_de_lali/lo_de_lali/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.cuentas.urls'), name='cuentas'),
    path('accounts/', include('django.contrib.auth.urls'), name="login"),
    path('tienda/', include('apps.tienda.urls'), name="tienda"),
]

proyecto_lo_de_lali/apps/cuentas/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey


# Create your models here.

#MODELO PARA MANEJAR EL REGISTRO DE CLIENTES
class cuentas_registradas (models.Model):
    id_cliente = models.AutoField(primary_key=True, auto_created=True)
    nombre = models.CharField("Nombre Cliente", max_length=30, blank=False, null=False, unique=True)
    debe = models.BooleanField("Tiene Saldo/ No tiene", default=False)
    total = models.FloatField("total", null=True, default=0)
    fecha = models.DateField(auto_now_add=True)
    celular = models.CharField("Celular", blank=False, unique=True, null=False, max_length=10)

    def __str__(self):
        x = f"{self.nombre} -------> cel: {self.celular}"
        return x
    
     
#MODELO PARA MANEJAR EL MOVIMIENTO DE CUENTAS DE CADA CLIENTE
class Resumen(models.Model):
    cliente = models.ForeignKey(cuentas_registradas, on_delete=models.CASCADE)
    fecha = models.DateField("fecha", auto_now_add=True)
    producto = models.CharField("producto", max_length=200)
    venta = models.FloatField("venta", default=0)
    entrega = models.FloatField("entrega", blank=True, null=True, default=0)
    saldo = models.FloatField("saldo", blank=True, null=True)
    total = models.FloatField("total", null=True, default=0)
    
    
    
    

    
    
    
    
    def __str__(self):
        x = "Cuenta de " + self.cliente.nombre
        return x

    

proyecto_lo_de_lali/apps/cuentas/forms.py
from django import forms
from django.db import models
from django.forms import fields, widgets
from .models import cuentas_registradas, Resumen

class FormularioResumen(forms.ModelForm):
    class Meta:
        model = Resumen
        fields = [
            "cliente",
            "producto",
            "venta",
            "entrega",
            
        ]
 
        labels = {
            "cliente":"Cliente",
            "producto": "Productos",
            "venta": "Venta",
            "entrega": "Entrega",
        }
        
        widgets = {
            'fecha': forms.DateInput(attrs={'type':'date'})
        }


 
class FormularioCuentas(forms.ModelForm):
    class Meta:
        model = cuentas_registradas
        fields = [ 
            "nombre",
            "celular",
            "debe",
        ]

        labels = {
            "nombre":"Nombre y Apellido",
            "celular":"Cel",
            "debe":"Ingresa con cuenta",
        }

        
        

proyecto_lo_de_lali/apps/cuentas/views.py
from django.core.exceptions import ObjectDoesNotExist
from .forms import FormularioCuentas, FormularioResumen
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from .models import cuentas_registradas, Resumen
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator


# Create your views here.
def index(request):
    #cuentas = FormularioCuentas()
    return render(request, 'index.html')


class Cuentas():
    # CARGAMOS LOS DATOS PARA EL REGISTRO DE UN NUEVO CLIENTE A LA BASE DE DATOS.
    @login_required
    def cargar_cuentas(request):
        
        if request.method == "POST":
            
            cuentas = FormularioCuentas(request.POST)

            mensaje = False
            if cuentas.is_valid():
                cuentas.save()
                

                if cuentas.save():
                    cuentas = FormularioCuentas()
                    messages.success(request, "¡Cuenta registrada con éxito!")
                    return redirect("lista_clientes")
                
            return render(request, 'cuentas/cargar_cuentas.html', {"form": cuentas, 'mensaje':mensaje})
        else: 
            cuentas = FormularioCuentas()
        return render(request, 'cuentas/cargar_cuentas.html', {"form": cuentas})



    # AGREGAMOS UN NUEVO MOVIMIENTO EN LA CUENTA DE ALGÚN CLIENTE YA REGISTRADO.
    @login_required
    def cargar_resumen(request, id_cliente):
        
        cliente = cuentas_registradas.objects.get(id_cliente = id_cliente)
        error = False
 
        if request.method == "POST":
            nuevo_resumen = FormularioResumen(request.POST)
            if nuevo_resumen.is_valid():
                nuevo_resumen.save()
                
                nuevo_resumen = Resumen.objects.filter(producto=request.POST["producto"]).last()
                total = cliente.total
                
                if total == None:
                    total = 0 

                venta = float(nuevo_resumen.venta)
                entrega = float(nuevo_resumen.entrega)
                
                if entrega == 0:
                    total += venta
                    
                    cliente.total = nuevo_resumen.total = nuevo_resumen.saldo = total
                else:
                    total += venta
                    saldo = total - entrega

                    nuevo_resumen.total = total
                    cliente.total = nuevo_resumen.saldo = saldo

                if cliente.total <= 0:
                    cliente.debe = False
                else:
                    cliente.debe = True

                cliente.save()

                nuevo_resumen.save()

                nuevo_resumen = FormularioResumen()


                return redirect("../lista_clientes")
            else:
                error = True

        nuevo_resumen = FormularioResumen()
        
        ctx={
            "form":nuevo_resumen,
            "cliente":cliente,
            "error":error,
        }
        return render(request, "cuentas/cargar_resumen.html", ctx)        


    # AGREGAMOS EL LINK EN EL NOMBRE DE CADA CLIENTE PARA QUE SE PUEDA ACCEDER A SU PLANILLA DE COMPRAS
    @login_required
    def ver_resumen(request, id_cliente):
        cliente = cuentas_registradas.objects.get(id_cliente = id_cliente)
        datos = Resumen.objects.filter(cliente = cliente)
        
        paginador = Paginator(datos, 5)
        pagina_actual = request.GET.get("page")
        datos = paginador.get_page(pagina_actual)


        ctx = {
            "cliente":cliente,
            "datos": datos #.order_by("fecha"),
        }

        return render(request, "cuentas/ver_resumen_cliente.html", ctx)


    # LISTA DE CLIENTES REGISTRADOS QUE TIENEN O NO DEUDA.
    @login_required
    def listar(request):
        buscar = request.GET.get("buscar")
        if buscar:
            cuentas = cuentas_registradas.objects.filter(nombre__icontains = buscar, debe = True)
            cuentas2 = cuentas_registradas.objects.filter(nombre__icontains = buscar, debe = False)
            # cuentas = cuentas_registradas.objects.filter(Q(nombre=buscar) | Q(apellido=buscar)).distinct()
        else:
            cuentas = cuentas_registradas.objects.filter(debe = True)
            cuentas2 = cuentas_registradas.objects.filter(debe = False)

        ctx = { 
            "cuentas": cuentas.order_by("nombre"),
            "cuentas2": cuentas2.order_by("nombre"),
        }
        
        return render(request, 'cuentas/lista_clientes.html', ctx)

    # ELIMINAR CUENTA
    def eliminar_cuenta(request, id_cliente):
        cuenta = cuentas_registradas.objects.get(id_cliente = id_cliente)
        cuenta.delete()
        return redirect('lista_clientes')

proyecto_lo_de_lali/templates/cuentas/cargar_cuentas.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Registro Cuenta</title>
{% endblock %}


{% block estilos %}
    <link href="{% static 'css/estilos.css' %} " rel="stylesheet">
{% endblock estilos %}

{% block content %}
    
    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            Verifique los datos ingresados. ¡Hay errores!
        </div>
    {% endif %}

    <div class="div_registro">
        <h1>Nueva Cuenta</h1>
        <div>
            <form action="{% url 'cargar_cuentas' %}" method="POST"  class="form" > <!-- style="padding: 10px;" -->
                {% csrf_token %}

                
                {{form|crispy}}

                <button type="submit" class="btn btn-primary" >Registrar</button> <!-- style="margin-top: 25px;" -->

            </form>
        </div>
    </div>
    



{% endblock %}

proyecto_lo_de_lali/templates/cuentas/cargar_resumen.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>CARGAR RESUMEN</title>
{% endblock %}


{% block content %}
    
    {% if error %}
        <div class="alert alert-danger" role="alert" style="text-align: center;">
            Verifique los datos ingresados. ¡Hay errores!
        </div>
    {% endif %}
    
    <h1>Nueva Compra</h1>
     
    <!-- <form method="POST" style="padding: 10px;" class="form" >
        {% csrf_token %}

        {% if mensaje %}
            <div class="alert alert-primary" role="alert">
                ¡Cuenta registrada exitosamente!
            </div>
        {% endif %}

        

        {{form|crispy}}

        <button type="submit" class="btn btn-light" style="margin-top: 25px;">Registrar</button>

    </form>
 -->
    <form method="POST" style="padding: 10px;" class="form">
        {% csrf_token %}

        <div> <!-- id="div_id_id_cliente" style="margin: 20px;" -->
            <select name="cliente" required="" id="id_cliente">
                <option value={{cliente.id_cliente}} selected={{cliente.id_cliente}}>{{cliente}}</option>
            </select>
            <h2>Saldo ${{cliente.total}}</h2>
        </div>

        <div>  <!-- id="div_id_producto" class="form-group" -->
            <label for="id_producto" class="requiredField">Productos<span class="asteriskField">*</span> </label> 
            <div class=""> 
                <input type="text" name="producto" maxlength="200" class="textinput textInput form-control" id="id_producto" required> 
            </div> 
        </div>

        <div> <!--  id="div_id_venta" class="form-group" -->
            <label for="id_venta">Venta<span class="asteriskField">*</span> </label> 
            <div class=""> 
                <input type="number" name="venta" value="0" step="any" class="numberinput form-control" required="" id="id_venta"> 
            </div> 
        </div>

        <div>  <!--  id="div_id_entrega" class="form-group" -->
            <label for="id_entrega">Entrega</label> 
            <div> 
                <input type="number" name="entrega" value="0" step="any" class="numberinput form-control" id="id_entrega"> 
            </div> 
        </div>

        <button type="submit" class="btn btn-primary">Registrar</button> <!--  style="margin-top: 25px;" -->
    </form>

{% endblock %}

proyecto_lo_de_lali/templates/cuentas/error.html
{% extends 'base.html' %}

{% block title %}
    <title>ERROR</title>
{% endblock %}

{% block content %}





{% endblock %}

proyecto_lo_de_lali/templates/cuentas/lista_clientes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Lista Clientes</title>
    
{% endblock %}

{% block content %}


{% if messages %}
    <div class="alert alert-success" role="alert">
        {% for message in messages %}
            <div style="text-align: center; ">{{ message }}</div> <!-- Ver en viws método para pasar mensajes de alerta -->
        {% endfor %}
    </div>
{% endif %}

{% block buscar %}
<div class="div_registro">
    <form  method="GET"> <!-- style="padding: 8px 20px;" -->
        <div id="custom-search-input">
            <input class="form-control" style="text-align: center;" type="text" placeholder="Buscar Cliente..." aria-label="Search" name="buscar" value="{{ request.GET.buscar}}">            
        </div>           
    </form>
</div>
{% endblock buscar %}

<h1 style="border-bottom: black solid 2px;">Clientes</h1> 

<table border="1" class="table" style="text-align: center; margin-left: auto; margin-right: auto; width: 80%; font-family: Calibri;">
    
    <tr>
        <th class="table-primary">Id</th>
        <th class="table-primary" style="width: 230px;">Nombre Cliente</th>
        <th class="table-primary">Celular</th>
        <th class="table-primary">Fecha Alta</th>
        <th class="table-primary">Opciones</th>
    </tr>
    
    {% for cliente in cuentas %}
        <tr>
            <td class="table-danger">{{cliente.id_cliente}}</td>
            <td class="table-danger" style="text-align:left;"><a href="{% url 'ver_resumen' cliente.id_cliente %}">{{cliente.nombre|upper}}</a></td>    
            <td class="table-danger">{{cliente.celular}}</td>
            <td class="table-danger">{{cliente.fecha|date:'d-m-Y'}}</td>
            <td class="table-danger"> 
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                    <a href="{% url 'cargar_resumen' cliente.id_cliente %}"><button type="button" class="btn btn-success" style="background-color: rgb(130, 236, 130, .7);">✓</button></a>
                </div>
                <!-- <button class="btn btn-primary" style="background-color: rgb(191, 224, 245);" type="button"><a href="{% url 'cargar_resumen' cliente.id_cliente %}">Venta/entrega</a></button> -->
            </td> 
        </tr>
    {% endfor %}    
</table>

<h1 style="border-bottom: black solid 2px;">Clientes sin saldos</h1> 
<table border="1" class="table" style="text-align: center; margin-left: auto; margin-right: auto; width: 80%; font-family: Calibri;">
    <caption>Carlos Rudaz</caption> <!-- ESTO ES PARA PONER COMENTARIO DEBAJO DE LA TABLA-->
    <tr>
        <th class="table-primary">Id</th>
        <th class="table-primary">Nombre Cliente</th>
        <th class="table-primary">Celular</th>
        <th class="table-primary">Fecha Alta</th>
        <th class="table-primary">Opciones</th>
    </tr>
    
    {% for cliente in cuentas2 %}
        <tr>
            <td class="table-danger">{{cliente.id_cliente}}</td>
            <td class="table-danger"><a href="{% url 'ver_resumen' cliente.id_cliente %}">{{cliente.nombre|upper}}</a></td>    
            <td class="table-danger">{{cliente.celular}}</td>
            <td class="table-danger">{{cliente.fecha|date:'d-m-Y'}}</td>
            <td class="table-danger"> 
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                    <a href="{% url 'eliminar_cuenta' cliente.id_cliente %}" style="font-family: Calibri;"><button type="button" class="btn btn-danger" style=" width: 40px; background-color: rgba(236, 130, 130, 0.7);">X</button></a>
                    <a href="{% url 'cargar_resumen' cliente.id_cliente %}"><button type="button" class="btn btn-success" style="width: 40px; background-color: rgb(130, 236, 130, .7);">✓</button></a>
                </div>
                <!-- <button class="btn btn-primary" style="background-color: rgb(191, 224, 245);" type="button"><a href="{% url 'cargar_resumen' cliente.id_cliente %}">Venta/entrega</a></button> -->
            </td> 
        </tr>
    {% endfor %}    
</table>

<style>
    .table a{
        text-decoration: none;
    }
</style>
{% endblock %}

proyecto_lo_de_lali/templates/cuentas/ver_resumen_cliente.html
{% extends 'base.html' %}

{% block title %}
    <title>Resumen {{cliente.nombre}}</title>
{% endblock %}



{% block content %}

<h1 style="margin-top: 30px;">Resumen {{cliente.nombre.capitalize}}</h1>
<div class="lista_cuentas"> 
    
    
    <h3> Celular: {{cliente.celular}} </h3>
    {% if cliente.total > 0 %}
        <h3>Total Deuda: ${{cliente.total}}</h3>
    {% else %}
        <h3>Sin Deuda</h3>
        <h3>Saldo a favor: ${{cliente.total}}</h3>
    {% endif %}
    


    <table border="1" class="table">
        <tr>
            <th>Fecha</th>
            
            <th>Productos</th> 
            <th>Precio</th>
            <th>Total</th>
            <th>Entrega</th>
            <th>Saldo</th>
        </tr>
        
        {% for x in datos %}

            

            {% if cliente.total > 0  %}
                <tr>
                    
                    {% if "Entrega" in x.producto or "entrega" in x.producto %}
                        <td style="background-color: rgb(187, 186, 186);">{{x.fecha|date:'d-m-Y'}}</td>
                        <td style="background-color: rgb(187, 186, 186);">{{x.producto}}</td>
                        <td style="background-color: rgb(187, 186, 186);">{{x.venta}}</td>
                        <td style="background-color: rgb(187, 186, 186);">{{x.total}}</td>
                        <td style="background-color: rgb(187, 186, 186);">{{x.entrega}}</td>
                        <td style="background-color: rgb(187, 186, 186);">${{x.saldo}}</td>
                    {% else %}
                        <td>{{x.fecha|date:'d-m-Y'}}</td>
                        <td>{{x.producto}}</td>
                        <td>{{x.venta}}</td>
                        <td>{{x.total}}</td>
                        <td>{{x.entrega}}</td>
                        <td>${{x.saldo}}</td>
                    {% endif %}
                    
                </tr>
            {% else %} 
                <tr>
                    
                </tr>
            {% endif %}

            
            
        {% endfor %}
        
    </table>

    

</div>
<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group me-2" role="group" aria-label="First group">
        {% if datos.has_previous %}
            <button type="button" class="btn btn-outline-dark"><a href="?page=1">&laquo;</a></button>

            <button type="button" class="btn btn-outline-dark"><a href="?page={{ datos.previous_page_number }}">{{ datos.previous_page_number }} </a></button>

        {% endif %}

        
        <button type="button" class="btn btn-outline-dark">{{ datos.number }}</button>
       

        {% if datos.has_next %}
            
            <button type="button" class="btn btn-outline-dark"><a href="?page={{ datos.next_page_number }}">{{ datos.next_page_number }} </button></a>
            <button type="button" class="btn btn-outline-dark"><a href="?page={{ datos.paginator.num_pages }}">&raquo;</a></button>

            
        {% endif %}
    </div>
</div>



{% endblock %}